[workspace]
channels = ["chawyehsu", "https://prefix.dev/conda-forge"]
platforms = ["win-64"]
preview = ["pixi-build"]

[tasks]
clean = { cmd = "pixi clean", description = "Clean build artifacts" }
build = { cmd = "pixi build", description = "Build the project", depends-on = ["clean"] }

[dependencies]
detours = ">=4.0.1,<5"
nlohmann_json = ">=3.11.3,<4"
freetype = { path = "vendor/freetype" }
IniParser = { path = "vendor/IniParser" }

# ------------------ #
# Package definition #
# ------------------ #
[package]
name = "mactype"
authors = ["snowie2000 <mactype.feedback@gmail.com>"]
description = "Better font rendering for Windows"
version = "1.2025.409.1"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.host-dependencies]
detours = ">=4.0.1,<5"
nlohmann_json = ">=3.11.3,<4"
freetype = { path = "vendor/freetype" }
IniParser = { path = "vendor/IniParser" }
