[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "win-arm64"]
preview = ["pixi-build"]

[tasks]

[dependencies]
nlohmann_json = ">=3.11.3,<4"
freetype = { path = "vendor/freetype" }

# ------------------ #
# Package definition #
# ------------------ #
[package]
name = "mactype"
authors = ["snowie2000 <mactype.feedback@gmail.com>"]
description = "Better font rendering for Windows"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.host-dependencies]
nlohmann_json = ">=3.11.3,<4"
freetype = { path = "vendor/freetype" }
