[project]
name = "mactype"
version = "0.1.0"
description = "Better font rendering for Windows"
authors = ["snowie2000 <mactype.feedback@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
nlohmann_json = ">=3.11.3,<4"
